### ISSUE TITLE
refactor: get rid of counter-productive `region.start < region.end` checks

### ISSUE THREAD

**Issue by jarkkojs** [jarkkojs/mmledger#52]
While continuing to use `Region` internally is a solid and favorable idea, in the public API this causes gray hairs by generating an artificial corner case when `region.start > region.end`. In the `pub fn`'s it's better use (addr, length) and then convert that to a region.

Also, in most of the call sites a `Region` instance is created for the sole reason to make a ledger call, which feels a bit counter-productive.

**Comment by jarkkojs** [comment]
@npmccallum this was reported by @haraldh. So the question is does `Line<T, U>` have this check already built in?

**Comment by npmccallum** [comment]
@jarkkojs I don't remember. You'll have to look at the source code.

**Comment by jarkkojs** [comment]
> @jarkkojs I don't remember. You'll have to look at the source code.

OK, I'll take a peek.

**Comment by jarkkojs** [comment]
My experience after using this API for over a month is that `Region` makes sense as an internal data structure,  but not necessarily something visible in the API. Most of the time you construct a `Region` instance just to make function call. What you *actually* construct is `Address<usize, Page>` and `Offset<usize, Page>`.  So in pub fn's I would consider replacing `region: Region` with `addr: Address<usize, Page>, length: Offset<usize, Page>`. That would simplify the shim code in some places. @haraldh, @npmccallum: What's your opinion on this? *POST* release obviously.
